version: '3'
services:
    dykm_client:
        build:
            context: ./DYKM_Client
        container_name: "DYKM_Client"
        ports:
            - "3000:3000"
    dykm_server:
        build:
            context: ./DYKM_Server
        container_name: "DYKM_Server"
        ports:
            - "1337:1337"

